export const insuranceData = [
  {
    company_name: "UZBEKINVEST",
    username: "@uzbekinvest_",
    subscribers: 1020,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 81761,
    avg_views_per_month: 1009,
    avg_views_per_video: 750,
    avg_likes_per_video: 10,
    channel_created_date: "1/26/2019",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "IMPEX-INSURANCE",
    username: "@impexinsurance",
    subscribers: 597,
    total_videos: 69,
    avg_posts_per_month: 2,
    total_views: 141598,
    avg_views_per_month: 3421,
    avg_views_per_video: 2052,
    avg_likes_per_video: 27,
    channel_created_date: "5/16/2022",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "O'ZAGROSUG'URTA",
    username: "@uzagrosugurtsje3884",
    subscribers: 627,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 85256,
    avg_views_per_month: 1062,
    avg_views_per_video: 782,
    avg_likes_per_video: 5,
    channel_created_date: "2/18/2019",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "INSON",
    username: "@insonu.zbekistan",
    subscribers: 540,
    total_videos: 41,
    avg_posts_per_month: 2,
    total_views: 45135,
    avg_views_per_month: 1205,
    avg_views_per_video: 1102,
    avg_likes_per_video: 25,
    channel_created_date: "9/14/2022",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "KAFIL-SUG'URTA",
    username: "@KAFILSUGURTA",
    subscribers: 248,
    total_videos: 116,
    avg_posts_per_month: 2,
    total_views: 33058,
    avg_views_per_month: 375,
    avg_views_per_video: 287,
    avg_likes_per_video: 6,
    channel_created_date: "6/18/2018",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "KAFOLAT SUG'URTA KOMPANIYASI",
    username: "@kafolatzub",
    subscribers: 132,
    total_videos: 118,
    avg_posts_per_month: 5,
    total_views: 74810,
    avg_views_per_month: 3096,
    avg_views_per_video: 645,
    avg_likes_per_video: 6,
    channel_created_date: "10/23/2023",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "GROSS SUG'URTA KOMPANIYASI",
    username: "@gross_insurance",
    subscribers: 111,
    total_videos: 43,
    avg_posts_per_month: 1,
    total_views: 179766,
    avg_views_per_month: 1587,
    avg_views_per_video: 4181,
    avg_likes_per_video: 4,
    channel_created_date: "5/18/2016",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "HAMKOR SUG'URTA",
    username: "@HamkorSugurta-JSC",
    subscribers: 24,
    total_videos: 20,
    avg_posts_per_month: 2,
    total_views: 1005,
    avg_views_per_month: 64,
    avg_views_per_video: 50,
    avg_likes_per_video: 1,
    channel_created_date: "7/4/2024",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "NEO INSURANCE CORP",
    username: "@neoinsurance_uz",
    subscribers: 25,
    total_videos: 16,
    avg_posts_per_month: 2,
    total_views: 5708,
    avg_views_per_month: 391,
    avg_views_per_video: 357,
    avg_likes_per_video: 3,
    channel_created_date: "8/9/2024",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "SEMURG INSURANCE",
    username: "@semurginsurance4739",
    subscribers: 22,
    total_videos: 7,
    avg_posts_per_month: 1,
    total_views: 1519,
    avg_views_per_month: 31,
    avg_views_per_video: 217,
    avg_likes_per_video: 4,
    channel_created_date: "8/19/2021",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "MY-INSURANCE",
    username: "@myinsurance1870",
    subscribers: 20,
    total_videos: 4,
    avg_posts_per_month: 1,
    total_views: 1587,
    avg_views_per_month: 37,
    avg_views_per_video: 397,
    avg_likes_per_video: 6,
    channel_created_date: "3/1/2022",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "IMKON-SUG'URTA",
    username: "@imkonsugurta7940",
    subscribers: 17,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 779,
    avg_views_per_month: 18,
    avg_views_per_video: 390,
    avg_likes_per_video: 2,
    channel_created_date: "1/20/2022",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "ISHONCH SUG'URTA KOMPANIYASI",
    username: "@ishonchsugurtakompaniyasi7576",
    subscribers: 12,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 114,
    avg_views_per_month: 2,
    avg_views_per_video: 114,
    avg_likes_per_video: 2,
    channel_created_date: "5/23/2018",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "EUROASIA INSURANCE",
    username: "@euroasiansuгance1433",
    subscribers: 11,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 456,
    avg_views_per_month: 6,
    avg_views_per_video: 228,
    avg_likes_per_video: 2,
    channel_created_date: "4/4/2019",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "KAPITAL SUG'URTA",
    username: "@kapitalsugurta8955",
    subscribers: 10,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 1064,
    avg_views_per_month: 12,
    avg_views_per_video: 532,
    avg_likes_per_video: 1,
    channel_created_date: "5/17/2018",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "ALSKOM SUG'URTA KOMPANIYASI",
    username: "@alskom5348",
    subscribers: 5,
    total_videos: 3,
    avg_posts_per_month: 1,
    total_views: 174,
    avg_views_per_month: 4,
    avg_views_per_video: 58,
    avg_likes_per_video: 1,
    channel_created_date: "10/19/2021",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "ASIA INSURANCE SUG'URTA KOMPANIYASI",
    username: "@asiainsurance_UZ",
    subscribers: 3,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 11,
    avg_views_per_month: 1,
    avg_views_per_video: 11,
    avg_likes_per_video: 1,
    channel_created_date: "8/24/2021",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "SOB INSURANCE SUG'URTA KOMPANIYASI",
    username: "@sqbinsurance2835",
    subscribers: 2,
    total_videos: 19,
    avg_posts_per_month: 1,
    total_views: 677,
    avg_views_per_month: 15,
    avg_views_per_video: 36,
    avg_likes_per_video: 1,
    channel_created_date: "10/19/2021",
    last_updated_date: "10/31/2025",
  },
  {
    company_name: "ARIA SUG'URTA TASHKILOTI",
    username: "@ariainsurance8269",
    subscribers: 1,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 87,
    avg_views_per_month: 3,
    avg_views_per_video: 44,
    avg_likes_per_video: 1,
    channel_created_date: "8/5/2022",
    last_updated_date: "10/31/2025",
  },
];
