export const insuranceData = [
  {
    company_name: "Uzbekinvest",
    username: "@uzbekinvest_",
    subscribers: 1020,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 80874,
    avg_views_per_month: 1010,
    avg_views_per_video: 748,
    avg_likes_per_video: 10,
    channel_created_date: "1/26/2019",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Impex Insurance",
    username: "@impexinsurance",
    subscribers: 598,
    total_videos: 61,
    avg_posts_per_month: 2,
    total_views: 141314,
    avg_views_per_month: 3493,
    avg_views_per_video: 2112,
    avg_likes_per_video: 28,
    channel_created_date: "5/16/2022",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Uzagrosugurta",
    username: "@uzagrosugurtsje3884",
    subscribers: 591,
    total_videos: 108,
    avg_posts_per_month: 2,
    total_views: 83383,
    avg_views_per_month: 1051,
    avg_views_per_video: 781,
    avg_likes_per_video: 5,
    channel_created_date: "2/18/2019",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "INSON Sug'urta",
    username: "@insonu.zbekistan",
    subscribers: 521,
    total_videos: 41,
    avg_posts_per_month: 2,
    total_views: 42552,
    avg_views_per_month: 1165,
    avg_views_per_video: 1088,
    avg_likes_per_video: 25,
    channel_created_date: "9/14/2022",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "KAFIL SUG'URTA",
    username: "@KAFILSUGURTA",
    subscribers: 246,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 32290,
    avg_views_per_month: 370,
    avg_views_per_video: 290,
    avg_likes_per_video: 6,
    channel_created_date: "6/18/2018",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Kafolat Sug'urta",
    username: "@kafolatzub",
    subscribers: 130,
    total_videos: 111,
    avg_posts_per_month: 5,
    total_views: 68091,
    avg_views_per_month: 2931,
    avg_views_per_video: 649,
    avg_likes_per_video: 6,
    channel_created_date: "10/23/2023",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Gross Insurance",
    username: "@gross_insurance",
    subscribers: 112,
    total_videos: 43,
    avg_posts_per_month: 1,
    total_views: 179659,
    avg_views_per_month: 1599,
    avg_views_per_video: 4180,
    avg_likes_per_video: 4,
    channel_created_date: "5/18/2016",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Hamkor Sug'urta",
    username: "@HamkorSugurta-JSC",
    subscribers: 24,
    total_videos: 20,
    avg_posts_per_month: 2,
    total_views: 920,
    avg_views_per_month: 62,
    avg_views_per_video: 49,
    avg_likes_per_video: 1,
    channel_created_date: "7/4/2024",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Neo Insurance",
    username: "@neoinsurance_uz",
    subscribers: 24,
    total_videos: 16,
    avg_posts_per_month: 2,
    total_views: 5592,
    avg_views_per_month: 409,
    avg_views_per_video: 355,
    avg_likes_per_video: 3,
    channel_created_date: "8/9/2024",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Semurg Insurance",
    username: "@semurginsurance4739",
    subscribers: 21,
    total_videos: 7,
    avg_posts_per_month: 1,
    total_views: 1509,
    avg_views_per_month: 31,
    avg_views_per_video: 217,
    avg_likes_per_video: 4,
    channel_created_date: "8/19/2021",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "My Insurance",
    username: "@myinsurance1870",
    subscribers: 19,
    total_videos: 4,
    avg_posts_per_month: 1,
    total_views: 1547,
    avg_views_per_month: 37,
    avg_views_per_video: 395,
    avg_likes_per_video: 6,
    channel_created_date: "3/1/2022",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Imkon Sug'urta",
    username: "@imkonsuguгta7940",
    subscribers: 17,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 770,
    avg_views_per_month: 18,
    avg_views_per_video: 387,
    avg_likes_per_video: 2,
    channel_created_date: "1/20/2022",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Ishonch Sug'urta",
    username: "@ishonchsugurtakompaniyasi7576",
    subscribers: 12,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 114,
    avg_views_per_month: 2,
    avg_views_per_video: 114,
    avg_likes_per_video: 2,
    channel_created_date: "5/23/2018",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Euroasia Insurance",
    username: "@euroasiansuгance1433",
    subscribers: 11,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 450,
    avg_views_per_month: 6,
    avg_views_per_video: 228,
    avg_likes_per_video: 2,
    channel_created_date: "4/4/2019",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Kapital Sug'urta",
    username: "@kapitalsugurta8955",
    subscribers: 10,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 1042,
    avg_views_per_month: 12,
    avg_views_per_video: 528,
    avg_likes_per_video: 1,
    channel_created_date: "5/17/2018",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "ALSKOM Sug'urta",
    username: "@alskom5348",
    subscribers: 5,
    total_videos: 3,
    avg_posts_per_month: 1,
    total_views: 173,
    avg_views_per_month: 4,
    avg_views_per_video: 58,
    avg_likes_per_video: 1,
    channel_created_date: "10/19/2021",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "Asia Insurance",
    username: "@asiainsurance_UZ",
    subscribers: 3,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 11,
    avg_views_per_month: 1,
    avg_views_per_video: 11,
    avg_likes_per_video: 1,
    channel_created_date: "8/24/2021",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "SOB Insurance",
    username: "@sobinsurance2835",
    subscribers: 2,
    total_videos: 19,
    avg_posts_per_month: 1,
    total_views: 632,
    avg_views_per_month: 14,
    avg_views_per_video: 35,
    avg_likes_per_video: 1,
    channel_created_date: "10/19/2021",
    last_updated_date: "10/27/2025",
  },
  {
    company_name: "ARIA Insurance",
    username: "@ariainsurance8269",
    subscribers: 1,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 86,
    avg_views_per_month: 3,
    avg_views_per_video: 44,
    avg_likes_per_video: 1,
    channel_created_date: "8/5/2022",
    last_updated_date: "10/27/2025",
  },
];
