export const insuranceData = [
  {
    company_name: "UZBEKINVEST",
    username: "@uzbekinvest_",
    subscribers: 1050,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 84786,
    avg_views_per_month: 777.91,
    avg_views_per_video: 777.91,
    avg_likes_per_video: 10.45,
    channel_created_date: "1/26/2019",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "IMPEX-INSURANCE",
    username: "@impexinsurance",
    subscribers: 595,
    total_videos: 69,
    avg_posts_per_month: 2,
    total_views: 142320,
    avg_views_per_month: 2062.61,
    avg_views_per_video: 2062.61,
    avg_likes_per_video: 27.55,
    channel_created_date: "5/16/2022",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "O'ZAGROSUG'URTA",
    username: "@uzagrosugurtajsc3984",
    subscribers: 649,
    total_videos: 109,
    avg_posts_per_month: 2,
    total_views: 88041,
    avg_views_per_month: 2068.76,
    avg_views_per_video: 2068.76,
    avg_likes_per_video: 6.04,
    channel_created_date: "2/18/2019",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "INSON",
    username: "@insonuzbekistan",
    subscribers: 636,
    total_videos: 41,
    avg_posts_per_month: 2,
    total_views: 58635,
    avg_views_per_month: 1430.59,
    avg_views_per_video: 1430.59,
    avg_likes_per_video: 29.27,
    channel_created_date: "9/14/2022",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAFIL-SUG'URTA",
    username: "@KAFILSUGURTA",
    subscribers: 262,
    total_videos: 128,
    avg_posts_per_month: 2,
    total_views: 34637,
    avg_views_per_month: 319.96,
    avg_views_per_video: 319.96,
    avg_likes_per_video: 4.08,
    channel_created_date: "6/18/2018",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAFOLAT SUG'URTA KOMPANIYASI",
    username: "@kafolatuzb",
    subscribers: 156,
    total_videos: 138,
    avg_posts_per_month: 5,
    total_views: 94250,
    avg_views_per_month: 744.12,
    avg_views_per_video: 744.12,
    avg_likes_per_video: 6.82,
    channel_created_date: "10/23/2023",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "GROSS SUG'URTA KOMPANIYASI",
    username: "@gross_insurance",
    subscribers: 123,
    total_videos: 43,
    avg_posts_per_month: 1,
    total_views: 180168,
    avg_views_per_month: 4190.02,
    avg_views_per_video: 4190.02,
    avg_likes_per_video: 4.02,
    channel_created_date: "5/18/2016",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "HAMKOR SUG'URTA",
    username: "@HamkorSugurta-JSC",
    subscribers: 26,
    total_videos: 20,
    avg_posts_per_month: 2,
    total_views: 1292,
    avg_views_per_month: 64.6,
    avg_views_per_video: 64.6,
    avg_likes_per_video: 1.3,
    channel_created_date: "7/4/2024",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "NEO INSURANCE CORP",
    username: "@neoinsurance_uz",
    subscribers: 25,
    total_videos: 16,
    avg_posts_per_month: 2,
    total_views: 6184,
    avg_views_per_month: 386.5,
    avg_views_per_video: 386.5,
    avg_likes_per_video: 2.81,
    channel_created_date: "8/9/2024",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "SEMURG INSURANCE",
    username: "@semurginsurance4739",
    subscribers: 23,
    total_videos: 7,
    avg_posts_per_month: 1,
    total_views: 1550,
    avg_views_per_month: 221.43,
    avg_views_per_video: 221.43,
    avg_likes_per_video: 3.86,
    channel_created_date: "8/19/2021",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "MY-INSURANCE",
    username: "@myinsurance1870",
    subscribers: 21,
    total_videos: 4,
    avg_posts_per_month: 1,
    total_views: 1776,
    avg_views_per_month: 444,
    avg_views_per_video: 444,
    avg_likes_per_video: 6,
    channel_created_date: "3/1/2022",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "IMKON-SUG'URTA",
    username: "@imkonsugurta7940",
    subscribers: 19,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 890,
    avg_views_per_month: 445.5,
    avg_views_per_video: 445.5,
    avg_likes_per_video: 2,
    channel_created_date: "1/20/2022",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ISHONCH SUG'URTA KOMPANIYASI",
    username: "@ishonchsugurtakompaniyasi7576",
    subscribers: 12,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 115,
    avg_views_per_month: 115,
    avg_views_per_video: 115,
    avg_likes_per_video: 2,
    channel_created_date: "5/23/2018",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "EUROASIA INSURANCE",
    username: "@euroasiainsurance1433",
    subscribers: 11,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 477,
    avg_views_per_month: 238.5,
    avg_views_per_video: 238.5,
    avg_likes_per_video: 1.5,
    channel_created_date: "4/4/2019",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "KAPITAL SUG'URTA",
    username: "@kapitalsugurta8955",
    subscribers: 11,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 1129,
    avg_views_per_month: 564.5,
    avg_views_per_video: 564.5,
    avg_likes_per_video: 1,
    channel_created_date: "5/17/2018",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ALSKOM SUG'URTA KOMPANIYASI",
    username: "@alskom5348",
    subscribers: 5,
    total_videos: 3,
    avg_posts_per_month: 1,
    total_views: 187,
    avg_views_per_month: 62.33,
    avg_views_per_video: 62.33,
    avg_likes_per_video: 1.33,
    channel_created_date: "10/19/2021",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ASIA INSURANCE SUG'URTA KOMPANIYASI",
    username: "@asiainsurance_UZ",
    subscribers: 3,
    total_videos: 1,
    avg_posts_per_month: 1,
    total_views: 11,
    avg_views_per_month: 11,
    avg_views_per_video: 11,
    avg_likes_per_video: 0,
    channel_created_date: "8/24/2021",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "SQB INSURANCE SUG'URTA KOMPANIYASI",
    username: "@sqbinsurance2835",
    subscribers: 2,
    total_videos: 19,
    avg_posts_per_month: 1,
    total_views: 817,
    avg_views_per_month: 43,
    avg_views_per_video: 43,
    avg_likes_per_video: 0.11,
    channel_created_date: "10/19/2021",
    last_updated_date: "1/2/2026",
  },
  {
    company_name: "ARIA SUG'URTA TASHKILOTI",
    username: "@ariainsurance8269",
    subscribers: 26,
    total_videos: 2,
    avg_posts_per_month: 1,
    total_views: 140,
    avg_views_per_month: 70,
    avg_views_per_video: 70,
    avg_likes_per_video: 8,
    channel_created_date: "8/5/2022",
    last_updated_date: "1/2/2026",
  },
];
